# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: New action Jose

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: 'Hello World'
        run: echo "Hello World"
