# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      # - name: Check out reusable worflows code (descargar los scripts auxiliares) => Fastlane

      - name: Setup Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.3.app
      - name: Setup Fastlane
        run: sudo gem install fastlane -NV
      - name: Get current date
        run: echo "Current date is $(date)"
      # - name: Decode signing certificate into a file
      # - name: Build Debug (using fastlane)
      # - name: Run Unit Testing (if needed)
      # - name: Run Lint (if needed)
      # - name: Run SonarCube (if needed)
      # - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
      #   with:
      #     swift-version: "5.5"
